name: PR Automation Test

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World from GitHub Actions"

      - name: Print PR Number
        run: echo "PR Number is ${{ github.event.pull_request.number }}"
